name: Deploy Lambda with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python for dependency installation
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Install dependencies and create deployment package
      - name: Build Lambda deployment package
        run: |
          mkdir -p package
          pip install requests -t package/
          cp lambda_function.py package/
          cd package
          zip -r ../package.zip .
          cd ..
          rm -rf package
        shell: bash

      - name: Install flake8
        run: pip install flake8

      - name: Install pytest
        run: pip install pytest

      - name: Run Linting
        run: flake8 lambda_function.py # Lint for python best practices

      - name: Run tests
        run: |
          ls -R
          pytest --verbose

      # Install Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Export AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-2"

      # Terraform Init
      - name: Initialize Terraform
        run: terraform init

      # Terraform Plan
      - name: Plan Terraform
        run: terraform plan

      # Terraform Apply
      - name: Apply Terraform
        run: terraform apply -auto-approve
